import streamlit as st
from datetime import datetime
from ai_strategy import AIManager
from database import save_to_supabase, get_supabase_client

st.set_page_config(layout="wide", page_title="AI-frikaans Assistant")

# Custom CSS
st.markdown("""
    <style>
    div[data-testid="stColumn"]:nth-of-type(1) button { background-color: #28a745 !important; color: white !important; }
    div[data-testid="stColumn"]:nth-of-type(2) button { background-color: #dc3545 !important; color: white !important; }
    </style>
    """, unsafe_allow_html=True)

AI_CONFIG = {
    "active_model": "ChatGPT 5.2",
    "system_instruction": "You are an Afrikaans assistant. You must make sure you are not using Dutch or German in your responses. Use html to help manage your responses. You must always explain the concept in both English and Afrikaans. Make use of STOMPI regarding sentence structure."
}

# State Initialization
if "session_id" not in st.session_state:
    st.session_state["session_id"] = datetime.now().strftime("%Y%m%d_%H%M%S")
if "messages" not in st.session_state: st.session_state["messages"] = []
if "feedback_pending" not in st.session_state: st.session_state["feedback_pending"] = False
if "authenticated" not in st.session_state: st.session_state["authenticated"] = False
if "current_user" not in st.session_state: st.session_state["current_user"] = None

# Unified function to get AI response, stream to UI, and log to DB.
def generate_ai_response(interaction_type):
    st.session_state["is_generating"] = True
    st.session_state["feedback_pending"] = False

    with st.chat_message("assistant"):
        # We use st.empty() as a container for the stream
        placeholder = st.empty()
        full_res = ""
        actual_model = AI_CONFIG["active_model"]
        ai_manager = AIManager(AI_CONFIG["active_model"])

        with st.spinner("Besig om te dink..."):
            for chunk, model_label in ai_manager.get_response_stream(
                    st.session_state["messages"],
                    AI_CONFIG["system_instruction"]
            ):
                full_res += chunk
                actual_model = model_label

                # Use unsafe_allow_html=True to ensure any HTML tags
                # generated by the AI are rendered, not stripped.
                placeholder.markdown(full_res, unsafe_allow_html=True)

    # Finalize the UI state
    st.session_state["messages"].append({"role": "assistant", "content": full_res})
    st.session_state["last_model_used"] = actual_model
    st.session_state["feedback_pending"] = True
    st.session_state["is_generating"] = False

    last_row_id = save_to_supabase(
        st.session_state["current_user"],
        actual_model,
        st.session_state["messages"],
        interaction_type,
        st.session_state["session_id"]
    )
    st.session_state["last_log_id"] = last_row_id  # Store it!
    st.rerun()

###########################
###        Sidebar      ###
###########################

if "authenticated" not in st.session_state:
    st.session_state["authenticated"] = False

with st.sidebar:
    st.image("icdf.png")

    if not st.session_state["authenticated"]:
        st.info("Enter your username and password below!")

        # Added .strip() to prevent invisible spaces from breaking the login
        username = st.text_input("Enter Username").strip()
        password = st.text_input("Enter Password", type="password").strip()

        if st.button("Login", use_container_width=True):
            # Using .get() prevents a crash if the credentials block isn't found
            if username in st.secrets.get("credentials", {}) and st.secrets["credentials"][username] == password:
                st.session_state.update({"authenticated": True, "current_user": username})
                st.rerun()
            else:
                st.error("Incorrect username or password.")

    else:
        st.write(f"Logged in as: {st.session_state['current_user']}")

        col1, col2 = st.columns(2)
        with col1:
            if st.button("Logout", use_container_width=True):
                st.cache_data.clear()
                st.session_state.clear()
                st.rerun()
        with col2:
            st.link_button("Feedback", "https://forms.office.com/r/zCqVE7mGzu",
                           use_container_width=True)

        st.divider()

        if st.button("New Chat", use_container_width=True):
            st.session_state.update({
                "messages": [],
                "session_id": datetime.now().strftime("%Y%m%d_%H%M%S"),
                "feedback_pending": False
            })
            st.rerun()
###########################
###        Sidebar      ###
###########################


###########################
###        Main         ###
###########################
st.image("combined_logo.jpg")
st.title("AI-frikaans Assistant")

if not st.session_state["authenticated"]:
    st.warning("Please login via the sidebar.")
    st.info("Welcome to the AIfrikaans Assistant Streamlit App!\n You are welcome to ask all your afrikaans related questions here. \n\n"
            "All your prompts and generated responses are recorded while using the app. You will be asked for feedback after each questions. "
            "If you click the \"I need more help\" button, the large language model will try and be more detailed in its explanation to try assist you learn!"
            "\n\nPlease remember that large language models are not perfect and are prone to hallucinations or representing false information as fact quite convincingly")
    st.stop()

# 1. Process pending feedback FIRST (before rendering anything else).
#    This block runs during the automatic rerun that follows the on_click callback.
#    At this point feedback_pending is already False (set in handle_feedback),
#    so the feedback buttons will not render this cycle — no duplicate UI.
if "pending_feedback_value" in st.session_state:
    # 1. Pop the state so this block only runs once per feedback cycle
    understood = st.session_state.pop("pending_feedback_value")
    log_id = st.session_state.get("last_log_id")

    if log_id:
        supabase = get_supabase_client()
        if understood:
            # UPDATE existing row for positive feedback
            supabase.table("chat_logs").update({"user_understood": True}).eq("id", log_id).execute()
        else:
            # UPDATE existing row for negative feedback
            supabase.table("chat_logs").update({"user_understood": False}).eq("id", log_id).execute()

            # 2. Retrieve the text the user typed in the form (Section 5)
            # If they typed nothing, it defaults to the generic string
            raw_text = st.session_state.pop("user_provided_clarification", "").strip()
            clarification_text = raw_text if raw_text else "I need more help. Please explain the previous response in more detail to help me learn."

            # 3. Add the user's specific (or generic) request to the chat history
            st.session_state["messages"].append({"role": "user", "content": clarification_text})

            # 4. Save this new 'Clarification Request' as its own entry in Supabase
            save_to_supabase(
                st.session_state["current_user"],
                st.session_state.get("last_model_used"),
                st.session_state["messages"],
                "CLARIFICATION_REQUEST",
                st.session_state["session_id"]
            )

            # 5. Flag the AI to respond to this new prompt
            st.session_state["trigger_clarification"] = True

# 1b. Process Translation Request
if st.session_state.get("pending_translation"):
    st.session_state.pop("pending_translation")
    log_id = st.session_state.get("last_log_id")

    # 1. Update DB to show translation was requested for the previous response
    if log_id:
        supabase = get_supabase_client()
        supabase.table("chat_logs").update({"translation_requested": True}).eq("id", log_id).execute()

    # 2. Add translation prompt to history
    trans_prompt = "Please translate your previous response into English."
    st.session_state["messages"].append({"role": "user", "content": trans_prompt})

    # 3. Log the request itself
    save_to_supabase(
        st.session_state["current_user"],
        st.session_state.get("last_model_used"),
        st.session_state["messages"],
        "TRANSLATE_REQUEST",
        st.session_state["session_id"]
    )

    # 4. Trigger the AI response
    st.session_state["trigger_translation_ai"] = True
# 2. Display Chat History
for msg in st.session_state["messages"]:
    role_label = "Assistant" if msg["role"] == "assistant" else st.session_state["current_user"]
    with st.chat_message(msg["role"]):
        st.write(f"**{role_label}:**")
        # Ensure history also renders the HTML/Structure
        st.markdown(msg["content"], unsafe_allow_html=True)

# 3. Trigger clarification AI response if flagged
if st.session_state.get("trigger_clarification"):
    st.session_state["trigger_clarification"] = False
    generate_ai_response("CLARIFICATION_RESPONSE")

# 3b. Trigger Translation AI response
if st.session_state.get("trigger_translation_ai"):
    st.session_state["trigger_translation_ai"] = False
    generate_ai_response("TRANSLATE_RESPONSE")

# 4. Chat Input
input_msg = "Please provide feedback..." if st.session_state["feedback_pending"] else "Ask your afrikaans question here"
if prompt := st.chat_input(input_msg, disabled=st.session_state["feedback_pending"]):
    st.session_state["messages"].append({"role": "user", "content": prompt})

    save_to_supabase(
        st.session_state["current_user"],
        AI_CONFIG["active_model"],
        st.session_state["messages"],
        "USER_PROMPT",
        st.session_state["session_id"]
    )
    st.rerun()

# 5. Feedback UI — only shown when a response is complete and not currently generating
if (
        st.session_state["messages"]
        and st.session_state["messages"][-1]["role"] == "assistant"
        and st.session_state["feedback_pending"]
        and not st.session_state.get("is_generating", False)
):
    if not st.session_state.get("show_clarification_input"):
        st.info("Please provide feedback or request a translation!")
        # Create 3 columns instead of 2
        c1, c2, c3 = st.columns(3)

        if c1.button("I understand!", use_container_width=True):
            st.session_state["feedback_pending"] = False
            st.session_state["pending_feedback_value"] = True
            st.rerun()

        if c2.button("I need more help!", use_container_width=True):
            st.session_state["show_clarification_input"] = True
            st.rerun()

        # NEW: Translation Button
        if c3.button("Translate to English", use_container_width=True):
            st.session_state["pending_translation"] = True
            st.session_state["feedback_pending"] = False
            st.rerun()

    # STEP B: Clarification Form (Opens only after clicking help)
    else:
        with st.form("clarification_form", clear_on_submit=True):
            st.markdown("### ✍️ How can I help further?")
            user_text = st.text_area(
                "Tell me what was unclear (or leave blank for a general explanation):",
                placeholder="e.g. Can you explain the STOMPI rule in that last sentence?"
            )

            # Create two columns for the buttons
            col_submit, col_cancel = st.columns(2)

            # The green/primary button
            submit_help = col_submit.form_submit_button(
                "Ask for clarification",
                use_container_width=True,
                type="primary"
            )

            # The cancel button
            cancel_help = col_cancel.form_submit_button(
                "Cancel",
                use_container_width=True
            )

            if submit_help:
                final_text = user_text.strip() if user_text.strip() else "I need more help. Please provide a more detailed explanation of your previous response."
                st.session_state["user_provided_clarification"] = final_text
                st.session_state["pending_feedback_value"] = False
                st.session_state["feedback_pending"] = False
                st.session_state["show_clarification_input"] = False
                st.rerun()

            if cancel_help:
                # Simply turn off the input flag and rerun to show the original buttons
                st.session_state["show_clarification_input"] = False
                st.rerun()
# 6. Generate Standard Response
if (
    st.session_state["messages"]
    and st.session_state["messages"][-1]["role"] == "user"
    and not st.session_state["feedback_pending"]
    and not st.session_state.get("trigger_clarification")
):
    generate_ai_response("GENERATED_RESPONSE")
###########################
###        Main         ###
###########################
